services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/lms
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api

volumes:
  mongo_data:
